<?php

/**
 * @file
 * Contains qwmaintenance.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qwmaintenance_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qwmaintenance module.
    case 'help.page.qwmaintenance':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maintenance functionality for Qwizard module.') . '</p>';
      return $output;

    default:
  }
}
