<?php

/**
 * @file
 * Contains qwschools.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qwschools_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qwschools module.
    case 'help.page.qwschools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a school entity type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function qwschools_theme() {
  $theme = [];
  $theme['school'] = [
    'render element' => 'elements',
    'file' => 'school.page.inc',
    'template' => 'school',
  ];
  $theme['school_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'school.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function qwschools_theme_suggestions_school(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#school'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'school__' . $sanitized_view_mode;
  $suggestions[] = 'school__' . $entity->bundle();
  $suggestions[] = 'school__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'school__' . $entity->id();
  $suggestions[] = 'school__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
